In [2]:
if 1<2:
    print('yep!')
    

yep!


In [6]:
my_list =[1,2,3]

In [9]:
import numpy as np

In [12]:
arr = np.array(my_list)

In [15]:
arr

array([1, 2, 3])

In [16]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.random.rand(5,5)

array([[0.41994833, 0.01640801, 0.88616843, 0.16473412, 0.98798239],
       [0.95786969, 0.72814669, 0.10359944, 0.09103564, 0.57572971],
       [0.94818036, 0.97119712, 0.05104934, 0.95334102, 0.29051315],
       [0.69755933, 0.4064815 , 0.70865286, 0.49809627, 0.06609715],
       [0.08663904, 0.33294203, 0.5342578 , 0.93834951, 0.42842184]])

In [21]:
np.random.rndn(2)

AttributeError: module 'numpy.random' has no attribute 'rndn'

In [23]:
np.random.rand(4,4)

array([[0.77460302, 0.78714102, 0.82252883, 0.86504341],
       [0.65149636, 0.40993091, 0.71394049, 0.44260985],
       [0.52604383, 0.61936999, 0.94685487, 0.84858671],
       [0.47505969, 0.12098799, 0.5134663 , 0.61867024]])

In [24]:
arr=np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.